# Generated by Django 4.1.4 on 2023-01-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="entrega",),
        migrations.RemoveField(model_name="gato", name="fecha_aprox_nacimiento",),
    ]
