# Generated by Django 4.1.4 on 2023-01-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Portfolio", "0002_delete_entrega_remove_gato_fecha_aprox_nacimiento"),
    ]

    operations = [
        migrations.RemoveField(model_name="adopcion", name="cantidad_mascotas",),
    ]
